# Shell variables
# Generated by 'wal'
wallpaper='/home/jordi/.config/wallpapers/bad-goisern.jpg'

# Special
background='#111010'
foreground='#d1cecf'
cursor='#d1cecf'

# Colors
color0='#111010'
color1='#36688F'
color2='#4D779D'
color3='#3D82AC'
color4='#5986AE'
color5='#6A91B6'
color6='#739EC5'
color7='#d1cecf'
color8='#929090'
color9='#36688F'
color10='#4D779D'
color11='#3D82AC'
color12='#5986AE'
color13='#6A91B6'
color14='#739EC5'
color15='#d1cecf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
