# Shell variables
# Generated by 'wal'
wallpaper='/home/jordi/.config/wallpapers/wallpaper_111.jpg'

# Special
background='#0d0c12'
foreground='#f0c4bf'
cursor='#f0c4bf'

# Colors
color0='#0d0c12'
color1='#98354A'
color2='#CC3852'
color3='#A84959'
color4='#DE5E66'
color5='#F0867B'
color6='#E67D82'
color7='#f0c4bf'
color8='#a88985'
color9='#98354A'
color10='#CC3852'
color11='#A84959'
color12='#DE5E66'
color13='#F0867B'
color14='#E67D82'
color15='#f0c4bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
