--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jordi/.config/wallpapers/bad-goisern.jpg"

-- Special
background="#111010"
foreground="#d1cecf"
cursor="#d1cecf"

-- Colors
color0="#111010"
color1="#36688F"
color2="#4D779D"
color3="#3D82AC"
color4="#5986AE"
color5="#6A91B6"
color6="#739EC5"
color7="#d1cecf"
color8="#929090"
color9="#36688F"
color10="#4D779D"
color11="#3D82AC"
color12="#5986AE"
color13="#6A91B6"
color14="#739EC5"
color15="#d1cecf"
