--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jordi/.config/wallpapers/wallpaper_16.jpg"

-- Special
background="#0c0909"
foreground="#d1d6db"
cursor="#d1d6db"

-- Colors
color0="#0c0909"
color1="#5B6471"
color2="#8A6E57"
color3="#5C6C82"
color4="#6E7886"
color5="#7A8592"
color6="#949DA8"
color7="#d1d6db"
color8="#929599"
color9="#5B6471"
color10="#8A6E57"
color11="#5C6C82"
color12="#6E7886"
color13="#7A8592"
color14="#949DA8"
color15="#d1d6db"
