--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jordi/.config/wallpapers/wallpaper_111.jpg"

-- Special
background="#0d0c12"
foreground="#f0c4bf"
cursor="#f0c4bf"

-- Colors
color0="#0d0c12"
color1="#98354A"
color2="#CC3852"
color3="#A84959"
color4="#DE5E66"
color5="#F0867B"
color6="#E67D82"
color7="#f0c4bf"
color8="#a88985"
color9="#98354A"
color10="#CC3852"
color11="#A84959"
color12="#DE5E66"
color13="#F0867B"
color14="#E67D82"
color15="#f0c4bf"
